name: Build & Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed --name Vulpin main.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Vulpin.exe

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build Linux binary
        run: |
          pyinstaller --onefile --name vulpin main.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/vulpin
