name: Vulide

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cp path/to/compiler build/vulpin

      - uses: softprops/action-gh-release@v2
        with:
          files: build/*
